### ISSUE TITLE
Generic Problem Statement needs work (sec 2)

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#12]
Hannes highlighted in https://mailarchive.ietf.org/arch/msg/scitt/XbpBlVZvzDToC0oPnmzYC62fQFE:

> In Section 2 is not a problem description. You could turn it into one if you give a few example of attacks and describe those. I think that this would be useful.

**Comment by yogeshbdeshpande** [comment]
@henkbirkholz : This has been addressed!

**Comment by hannestschofenig** [comment]
Please close the issue.

**Comment by yogeshbdeshpande** [comment]
Rework started with edits from @henkbirkholz. @yogeshbdeshpande and @kaywilliams 

The document is now having final reviews. This issue has been addresses, hence closing the issue!
