### ISSUE TITLE
Use of term "trust" in "Trust Bond between Package Supplier and the Signing Authority" (sec 4.1)

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#14]
Hannes highlighted in https://mailarchive.ietf.org/arch/msg/scitt/XbpBlVZvzDToC0oPnmzYC62fQFE:

> Every time you use the term “trust” think about an alternative word that could be used. For example, if I – as a Supplier -- write a software library, such as Mbed TLS, why do I need to use a “Signing Authority”? What do I need to tell that party to sign my software package. What exactly does it tell the consumer when they receive a signed software package? If you tell me the answers, try to avoid the terms “trust bond” and “trust”.

**Comment by yogeshbdeshpande** [comment]
TO DO: Few places Trust is reffered..

Need to correct using a PR.

**Comment by hannestschofenig** [comment]
Kay volunteered

**Comment by yogeshbdeshpande** [comment]
The Pull Request above is now Merged hence closing this issue!
