### ISSUE TITLE
Minor proposed change in use case 3.2

### ISSUE THREAD

**Issue by rjb4standards** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#19]
I have no concerns with the revised language for 3.1. One minor nit on 3.2 to be consistent with the use case title
REPLACE:
A consumer of released software component wants:
WITH
A consumer of released software product wants:

**Comment by kaywilliams** [comment]
LGTM

**Comment by yogeshbdeshpande** [comment]
This issue has been resolved in the above PR.
