### ISSUE TITLE
Slight modification to use case 3.1

### ISSUE THREAD

**Issue by rjb4standards** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#20]
Please add "and is still valid" - see new proposed langauge

enable the consumer to verify that software originated from a 'duly authorized signing party' on behalf of the Supplier, and is still valid

**Comment by kaywilliams** [comment]
+1 to this change

**Comment by yogeshbdeshpande** [comment]
Closing as been addressed now!
