### ISSUE TITLE
To-do List from the 13 February 2023 revision of Use Case

### ISSUE THREAD

**Issue by knight-brian** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#25]
Capturing to-do list for future action.

- Promotion Scenario: '3rd party lab validates the detail instead of their own test'
- Endorsement Scenario: Audit downstream independent of issuer and provide an endorsement
- CI/CD SCITT interaction - Create a model before talking to Github (Statements about SW could be listed. Policy management can be done via SCITT through SW development lifecycle)

**Comment by yogeshbdeshpande** [comment]
@knight-brian : Thank you for the help in creating the issue.

 The second bullet about Auditing is already addressed via section 3.5 -> Auditing of Software Product

**Comment by yogeshbdeshpande** [comment]
Bullet 3: is more like a specific profile of general architecture, not sure Use Case Document is the right one to host Bullet 3

**Comment by yogeshbdeshpande** [comment]
And First bullet is already addressed by presumably section 3.1

**Comment by yogeshbdeshpande** [comment]
@henkbirkholz @knight-brian @kaywilliams @rjb4standards 

Please have a look at the new document and let me know, if you agree/dis-agree with my observations on the TO DO list pending items.

**Comment by knight-brian** [comment]
@yogeshbdeshpande Thank you. I agree with your rationale for the three bullets.  I vote to close this issue, pending feedback from others.

**Comment by kaywilliams** [comment]
Agree.

**Comment by rjb4standards** [comment]
I also agree.

**Comment by knight-brian** [comment]
Bullets resolved. Closing issue "To-do List from the 13 February 2023 revision of Use Case #25."
