### ISSUE TITLE
Artefact vs. Artifact

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#28]
Which side of the pond shall we author the use cases?
https://www.grammar.com/artefact_vs._artifact

**Comment by henkbirkholz** [comment]
Artifact. The stray artefact is a typo. My spell checker also tells me that while I write this comment.

**Comment by yogeshbdeshpande** [comment]
Issue fixed via:
https://github.com/ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases/commit/5bfa128a2e7e967adc16b423f99aee18f0455747
