### ISSUE TITLE
Discuss possible methods of SBOM Deployment 

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#3]
SBOM's today are deployed by Suppliers through there designated portals.

What are the possible methods/Secure methods, as to how this can be enhanced considering Supply Chain Security.

**Comment by hannestschofenig** [comment]
Is this a topic for a use case document?

**Comment by yogeshbdeshpande** [comment]
No We will close this!
